services:
  - type: web
    name: attendance-backend
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
            name: attendance-db
            property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
            name: attendance-db
            property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
            name: attendance-db
            property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_JWT_SECRET
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_SECURITY_USER_NAME
        sync: false
      - key: SPRING_SECURITY_USER_PASSWORD
        sync: false
databases:
  - name: attendance-db
    plan: free