spring:
  datasource:
    url:  ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

  mail:
    smtp:
      auth: true
      starttls:
        enable: true
        required: true

server:
  error:
    include-stacktrace: never
    include-message: never