spring:
  application:
    name: Attendance

  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db
    username: root
    password: gourang123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

  security:
    user:
      name: gourang
      password: 1234

  jwt:
    secret: mysecretkey1234567890123456789012345678901234567890
    expiration: 86400000

server:
  port: ${SERVER_PORT:3000}
  error:
    include-stacktrace: never
    include-message: always